version: '3'
services:
  icontas-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: icontas/api
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=${SPRING_PROFILE}
    networks:
      - icarros_mysql
    depends_on:
      - mysqldb_icarros
      
  mysqldb_icarros:
      image: mysql:8
      env_file: .env
      ports:
      - "3306:3306"
      volumes:
        - ./db_mysql:/var/lib/mysql
      networks:
        - icarros_mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQLDB_DATABASE}
  
networks:
  icarros_mysql:
    driver: bridge